#!/usr/bin/env node
import { access, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import { constants } from "node:fs";
import { basename, join, resolve } from "node:path";

const EMIT_MARKER = "# --- Visualizer emit (auto-wired by bootstrap-existing-repo) ---";

interface CliOptions {
  targetRepo: string;
  prefix?: string;
  apply: boolean;
}

interface HookMapping {
  eventType: string;
}

interface HookCommand {
  type?: unknown;
  bash?: unknown;
  powershell?: unknown;
  [key: string]: unknown;
}

interface EmitStripResult {
  updated: string;
  removedBlocks: number;
}

interface ManifestRevertResult {
  updated: Record<string, unknown>;
  removedEvents: string[];
  changed: boolean;
}

const HOOK_MAP: Record<string, HookMapping> = {
  // .sh (bash) entries
  "session-start.sh": { eventType: "sessionStart" },
  "sessionstart.sh": { eventType: "sessionStart" },
  "session-end.sh": { eventType: "sessionEnd" },
  "sessionend.sh": { eventType: "sessionEnd" },
  "subagent-stop.sh": { eventType: "subagentStop" },
  "subagent-start.sh": { eventType: "subagentStart" },
  "log-prompt.sh": { eventType: "userPromptSubmitted" },
  "pre-tool-use.sh": { eventType: "preToolUse" },
  "post-tool-use.sh": { eventType: "postToolUse" },
  "post-tool-use-failure.sh": { eventType: "postToolUseFailure" },
  "agent-stop.sh": { eventType: "agentStop" },
  "notification.sh": { eventType: "notification" },
  "error-occurred.sh": { eventType: "errorOccurred" },
  // .ps1 (PowerShell) entries
  "session-start.ps1": { eventType: "sessionStart" },
  "sessionstart.ps1": { eventType: "sessionStart" },
  "session-end.ps1": { eventType: "sessionEnd" },
  "sessionend.ps1": { eventType: "sessionEnd" },
  "subagent-stop.ps1": { eventType: "subagentStop" },
  "subagent-start.ps1": { eventType: "subagentStart" },
  "log-prompt.ps1": { eventType: "userPromptSubmitted" },
  "pre-tool-use.ps1": { eventType: "preToolUse" },
  "post-tool-use.ps1": { eventType: "postToolUse" },
  "post-tool-use-failure.ps1": { eventType: "postToolUseFailure" },
  "agent-stop.ps1": { eventType: "agentStop" },
  "notification.ps1": { eventType: "notification" },
  "error-occurred.ps1": { eventType: "errorOccurred" },
};

const CANONICAL_HOOK_NAMES = (() => {
  const eventSeen = new Set<string>();
  const hyphenated = Object.keys(HOOK_MAP).filter((name) => name.includes("-"));
  const nonHyphenated = Object.keys(HOOK_MAP).filter((name) => !name.includes("-"));

  const result: string[] = [];
  for (const name of hyphenated) {
    const eventType = HOOK_MAP[name].eventType;
    if (!eventSeen.has(eventType)) {
      eventSeen.add(eventType);
      result.push(name);
    }
  }
  for (const name of nonHyphenated) {
    const eventType = HOOK_MAP[name].eventType;
    if (!eventSeen.has(eventType)) {
      eventSeen.add(eventType);
      result.push(name);
    }
  }
  return result;
})();

const EVENT_TO_CANONICAL_HOOK: Record<string, string> = CANONICAL_HOOK_NAMES.reduce<Record<string, string>>((acc, hookName) => {
  acc[HOOK_MAP[hookName].eventType] = hookName;
  return acc;
}, {});

/**
 * Name of the dedicated visualizer hook manifest created by bootstrap.
 */
const VISUALIZER_MANIFEST_NAME = "visualizer-hooks.json";

/**
 * Subdirectory under .github/hooks/ where visualizer-generated files live.
 */
const VISUALIZER_HOOKS_SUBDIR = "visualizer";

const STUB_SCRIPT_LINES = [
  "#!/usr/bin/env bash",
  "set -euo pipefail",
  "# Stub hook generated by bootstrap-existing-repo.",
  "# Add your custom logic above the visualizer emit block below.",
  "SCRIPT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)\"",
  "REPO_ROOT=\"$(cd \"$SCRIPT_DIR/../../..\" && pwd)\"",
  "exit 0",
] as const;

const STUB_SCRIPT_PS1_LINES = [
  "# Stub hook generated by bootstrap-existing-repo.",
  "# Add your custom logic above the visualizer emit block below.",
  "$ErrorActionPreference = \"Stop\"",
  "$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path",
  "$RepoRoot = (Resolve-Path (Join-Path $ScriptDir \"..\" \"..\" \"..\")).Path",
  "exit 0",
] as const;

/**
 * Legacy REPO_ROOT pattern (two levels up) used before stubs moved into
 * the visualizer/ subdirectory. Kept so unbootstrap can recognise old stubs.
 */
const LEGACY_REPO_ROOT_LINE = "REPO_ROOT=\"$(cd \"$SCRIPT_DIR/../..\" && pwd)\"";
const LEGACY_PS1_REPO_ROOT_LINE = "$RepoRoot = (Resolve-Path (Join-Path $ScriptDir \"..\" \"..\")).Path";

function fail(message: string): never {
  console.error(`unbootstrap-existing-repo error: ${message}`);
  process.exit(1);
}

function usage(): string {
  return [
    "Usage:",
    "  npm run unbootstrap:repo -- /absolute/path/to/target-repo [options]",
    "",
    "Options:",
    "  --apply            Apply changes (default is dry-run)",
    "  --prefix <name>    Prefix used during bootstrap (e.g. viz)",
    "  -h, --help         Show this help",
    "",
    "Dry-run mode prints planned removals without changing files.",
  ].join("\n");
}

function parseCliArgs(argv: string[]): CliOptions | null {
  const positional: string[] = [];
  let prefix: string | undefined;
  let apply = false;

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--prefix") {
      const value = argv[i + 1];
      if (!value || value.startsWith("--")) {
        fail("--prefix requires a value (e.g. --prefix viz)");
      }
      prefix = value;
      i += 1;
    } else if (arg === "--apply") {
      apply = true;
    } else if (arg === "-h" || arg === "--help") {
      console.log(usage());
      process.exit(0);
    } else if (!arg.startsWith("--")) {
      positional.push(arg);
    }
  }

  if (positional.length === 0) {
    return null;
  }

  return { targetRepo: positional[0], prefix, apply };
}

async function ensureExists(path: string): Promise<void> {
  try {
    await access(path, constants.F_OK);
  } catch {
    fail(`target repo does not exist: ${path}`);
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

export function stripVisualizerEmitBlocks(content: string): EmitStripResult {
  // Bash emit block pattern (ends with `fi`)
  const bashBlockPattern = new RegExp(
    `\\n?[\\t ]*${escapeRegExp(EMIT_MARKER)}\\n[\\s\\S]*?\\n[\\t ]*fi\\n?`,
    "g"
  );

  // PowerShell emit block pattern (ends with `}` alone on a line)
  // The closing `}` must be the only non-whitespace content on the line, so that
  // lines like `} catch { ... }` within the block are not matched prematurely.
  const ps1BlockPattern = new RegExp(
    `\\n?[\\t ]*${escapeRegExp(EMIT_MARKER)}\\n[\\s\\S]*?\\n([\\t ]*\\}[\\t ]*)(?=\\n|$)`,
    "g"
  );

  let removedBlocks = 0;
  let updated = content.replace(bashBlockPattern, () => {
    removedBlocks += 1;
    return "\n";
  });
  updated = updated.replace(ps1BlockPattern, () => {
    removedBlocks += 1;
    return "\n";
  });

  const normalized = updated.replace(/\n{3,}/g, "\n\n");
  return { updated: normalized, removedBlocks };
}

export function isAutoGeneratedStubContent(content: string): boolean {
  const nonEmptyLines = content
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0);

  // Old format: exactly STUB_SCRIPT_LINES.length lines matching the stub template
  if (nonEmptyLines.length === STUB_SCRIPT_LINES.length) {
    const oldFormatMatch = STUB_SCRIPT_LINES.every((line, idx) => {
      if (idx === 5) {
        // REPO_ROOT line — accept both new (3-level) and legacy (2-level) depth
        return nonEmptyLines[idx] === line || nonEmptyLines[idx] === LEGACY_REPO_ROOT_LINE;
      }
      return nonEmptyLines[idx] === line;
    });
    if (oldFormatMatch) return true;
  }

  // Check PowerShell stub (old format without stdin extraction)
  if (nonEmptyLines.length === STUB_SCRIPT_PS1_LINES.length) {
    return STUB_SCRIPT_PS1_LINES.every((line, idx) => {
      if (idx === 4) {
        // RepoRoot line — accept both new (3-level) and legacy (2-level) depth
        return nonEmptyLines[idx] === line || nonEmptyLines[idx] === LEGACY_PS1_REPO_ROOT_LINE;
      }
      return nonEmptyLines[idx] === line;
    });
  }

  // New format PS1: has stdin extraction block (after emit block was stripped).
  // Verify all lines are auto-generated PowerShell boilerplate with no user-added content.
  // Upper bound: old stub (6 lines) + stdin block (~27 lines) + extra comment = ~35 lines max.
  const PS1_MAX_AUTO_LINES = 50;
  if (nonEmptyLines.length > STUB_SCRIPT_PS1_LINES.length &&
      nonEmptyLines.length <= PS1_MAX_AUTO_LINES &&
      nonEmptyLines[0] === STUB_SCRIPT_PS1_LINES[0]) {
    // Verify this looks like a PS1 stub (has $ErrorActionPreference early in the file)
    const headerLines = nonEmptyLines.slice(0, STUB_SCRIPT_PS1_LINES.length);
    const hasErrPref = headerLines.some((l) => /^\$ErrorActionPreference\s*=/.test(l));
    if (!hasErrPref) {
      // Not a PS1 stub — fall through to bash checks below
    } else {
      if (nonEmptyLines[nonEmptyLines.length - 1] !== "exit 0") return false;

      const ps1AutoPatterns = [
        /^#/,                                    // comments
        /^\$ErrorActionPreference\s*=/,           // error preference
        /^\$ScriptDir\s*=/,                       // ScriptDir assignment
        /^\$RepoRoot\s*=/,                        // RepoRoot assignment
        /^\$_vizStdin\s*=/,                       // stdin capture (legacy: expression assignment)
        /^try\s*\{\s*\$_vizStdin\s*=/,            // stdin capture (statement form)
        /^if \(-not \$_vizStdin\)/,               // stdin empty check
        /^\$_vizJson\s*=/,                        // JSON parse (legacy: expression assignment)
        /^try\s*\{\s*\$_vizJson\s*=/,             // JSON parse (statement form)
        /^function _vizField/,                    // helper function (single line)
        /^function _vizNested/,                   // nested property helper (single line)
        /^if \(-not \$env:/,                      // env var assignments
        /^if \(\$env:STATUS/,                     // conditional postToolUse/failure routing
        /^\$_vizPayload\s*=/,                     // payload assignment
        /^& \$_vizEmitScript/,                    // emit-event invocation
        /^\} else \{/,                            // else branch
        /^\}/,                                    // closing brace
        /^exit 0$/,                               // exit
      ];

      return nonEmptyLines.every((line) =>
        ps1AutoPatterns.some((pattern) => pattern.test(line))
      );
    }
  }

  // New format bash: has stdin extraction block (after emit block was stripped).
  // Verify all lines are auto-generated boilerplate with no user-added content.
  if (nonEmptyLines.length < 3) return false;

  // Must start with shebang, set, and stub marker
  if (nonEmptyLines[0] !== STUB_SCRIPT_LINES[0]) return false;
  if (nonEmptyLines[1] !== STUB_SCRIPT_LINES[1]) return false;
  if (nonEmptyLines[2] !== STUB_SCRIPT_LINES[2]) return false;

  // Must end with exit 0
  if (nonEmptyLines[nonEmptyLines.length - 1] !== "exit 0") return false;

  // All lines must match known auto-generated patterns
  const autoPatterns = [
    /^#/,                              // comments
    /^set /,                           // set -euo pipefail
    /^SCRIPT_DIR=/,                    // SCRIPT_DIR assignment
    /^REPO_ROOT=/,                     // REPO_ROOT assignment
    /^_VIZ_STDIN=/,                    // stdin capture
    /^if \[ -z "\$_VIZ_STDIN" \]/,     // stdin empty check
    /^_vjq\(\)/,                       // jq helper function
    /^: "\$/,                          // : "${VAR:=...}" env var assignments
    /^if \[ "\$\{STATUS/,              // conditional postToolUse/failure routing
    /^_VIZ_PAYLOAD=/,                  // payload assignment
    /^"\$\{REPO_ROOT\}/,              // emit-event invocation
    /^else$/,                          // else branch
    /^fi$/,                            // fi (end of if block)
    /^exit 0$/,                        // exit
  ];

  return nonEmptyLines.every((line) =>
    autoPatterns.some((pattern) => pattern.test(line))
  );
}

function escapeRegExp(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function matchHookFilename(filename: string, prefix?: string): HookMapping | undefined {
  const lower = basename(filename).toLowerCase();

  const direct = HOOK_MAP[lower];
  if (direct) return direct;

  if (prefix) {
    const prefixPattern = new RegExp(`^${escapeRegExp(prefix.toLowerCase())}-`);
    const stripped = lower.replace(prefixPattern, "");
    if (stripped !== lower) {
      return HOOK_MAP[stripped];
    }
  }

  return undefined;
}

async function findShellScripts(dir: string): Promise<Array<{ relPath: string; absPath: string }>> {
  const results: Array<{ relPath: string; absPath: string }> = [];

  async function walk(currentDir: string, relBase: string): Promise<void> {
    let entries: string[];
    try {
      entries = await readdir(currentDir);
    } catch {
      return;
    }

    for (const entry of entries) {
      const absEntry = join(currentDir, entry);
      const relEntry = relBase ? join(relBase, entry) : entry;
      const info = await stat(absEntry);

      if (info.isDirectory()) {
        await walk(absEntry, relEntry);
      } else if (info.isFile() && (entry.endsWith(".sh") || entry.endsWith(".ps1"))) {
        results.push({ relPath: relEntry, absPath: absEntry });
      }
    }
  }

  await walk(dir, "");
  return results;
}

async function findJsonFiles(dir: string): Promise<Array<{ relPath: string; absPath: string }>> {
  const results: Array<{ relPath: string; absPath: string }> = [];

  async function walk(currentDir: string, relBase: string): Promise<void> {
    let entries: string[];
    try {
      entries = await readdir(currentDir);
    } catch {
      return;
    }

    for (const entry of entries) {
      const absEntry = join(currentDir, entry);
      const relEntry = relBase ? join(relBase, entry) : entry;
      const info = await stat(absEntry);

      if (info.isDirectory()) {
        await walk(absEntry, relEntry);
      } else if (info.isFile() && entry.endsWith(".json")) {
        results.push({ relPath: relEntry, absPath: absEntry });
      }
    }
  }

  await walk(dir, "");
  return results;
}

function expectedHookBashPaths(eventType: string, prefix?: string): string[] {
  const canonical = EVENT_TO_CANONICAL_HOOK[eventType];
  if (!canonical) return [];
  const filename = prefix ? `${prefix}-${canonical}` : canonical;
  const ps1Filename = filename.replace(/\.sh$/, ".ps1");
  return [
    `./.github/hooks/${VISUALIZER_HOOKS_SUBDIR}/${filename}`,
    `./.github/hooks/${filename}`,
    `./.github/hooks/${VISUALIZER_HOOKS_SUBDIR}/${ps1Filename}`,
    `./.github/hooks/${ps1Filename}`,
  ];
}

export function removeBootstrapManifestEntries(
  manifestRaw: unknown,
  prefix?: string
): ManifestRevertResult {
  if (!isRecord(manifestRaw) || !isRecord(manifestRaw.hooks)) {
    return { updated: isRecord(manifestRaw) ? { ...manifestRaw } : {}, removedEvents: [], changed: false };
  }

  const sourceHooks = manifestRaw.hooks;
  const hooks: Record<string, unknown> = { ...sourceHooks };
  const manifest: Record<string, unknown> = { ...manifestRaw, hooks };
  const removedEvents: string[] = [];
  let changed = false;

  for (const [eventType, value] of Object.entries(hooks)) {
    const expectedPaths = expectedHookBashPaths(eventType, prefix);
    if (expectedPaths.length === 0 || !Array.isArray(value)) {
      continue;
    }

    const commands = value as HookCommand[];
    const kept = commands.filter((cmd) => {
      if (!isRecord(cmd)) return true;
      if (cmd.type !== "command") return true;
      const bashMatch = typeof cmd.bash === "string" && expectedPaths.includes(cmd.bash);
      const ps1Match = typeof cmd.powershell === "string" && expectedPaths.includes(cmd.powershell);
      return !(bashMatch || ps1Match);
    });

    if (kept.length !== commands.length) {
      changed = true;
      removedEvents.push(eventType);
    }

    if (kept.length === 0) {
      delete hooks[eventType];
    } else {
      hooks[eventType] = kept;
    }
  }

  manifest.hooks = hooks;
  return { updated: manifest, removedEvents, changed };
}

async function main(): Promise<void> {
  const options = parseCliArgs(process.argv.slice(2));
  if (!options) {
    console.log(usage());
    process.exit(1);
  }

  const targetRepo = resolve(options.targetRepo);
  await ensureExists(targetRepo);

  const hooksDir = join(targetRepo, ".github", "hooks");
  const vizDir = join(targetRepo, ".visualizer");

  let hooksDirExists = true;
  try {
    await access(hooksDir, constants.F_OK);
  } catch {
    hooksDirExists = false;
  }

  const scriptChanges: string[] = [];
  const deletedStubs: string[] = [];
  const manifestChanges: string[] = [];
  const skipped: string[] = [];

  if (hooksDirExists) {
    const shellScripts = await findShellScripts(hooksDir);

    for (const { relPath, absPath } of shellScripts) {
      const content = await readFile(absPath, "utf8");
      const stripped = stripVisualizerEmitBlocks(content);
      if (stripped.removedBlocks === 0) {
        continue;
      }

      const normalizedRel = relPath.replaceAll("\\", "/");
      const mapping = matchHookFilename(relPath, options.prefix);
      const canDeleteStub = Boolean(mapping) && isAutoGeneratedStubContent(stripped.updated);

      if (canDeleteStub) {
        deletedStubs.push(`.github/hooks/${normalizedRel}`);
        if (options.apply) {
          await rm(absPath, { force: true });
        }
        continue;
      }

      scriptChanges.push(`.github/hooks/${normalizedRel}`);
      if (options.apply) {
        await writeFile(absPath, stripped.updated, "utf8");
      }
    }

    const manifests = await findJsonFiles(hooksDir);
    for (const { relPath, absPath } of manifests) {
      const manifestLabel = `.github/hooks/${relPath.replaceAll("\\", "/")}`;

      // Delete the dedicated visualizer manifest entirely
      if (basename(relPath) === VISUALIZER_MANIFEST_NAME) {
        deletedStubs.push(manifestLabel);
        if (options.apply) {
          await rm(absPath, { force: true });
        }
        continue;
      }

      let parsed: unknown;
      try {
        parsed = JSON.parse(await readFile(absPath, "utf8"));
      } catch {
        skipped.push(`${manifestLabel} (invalid JSON)`);
        continue;
      }

      const reverted = removeBootstrapManifestEntries(parsed, options.prefix);
      if (!reverted.changed) {
        continue;
      }

      manifestChanges.push(`${manifestLabel}: ${reverted.removedEvents.join(", ")}`);
      if (options.apply) {
        await writeFile(absPath, `${JSON.stringify(reverted.updated, null, 2)}\n`, "utf8");
      }
    }

    // Clean up the visualizer subdirectory if it's now empty
    const vizHooksDir = join(hooksDir, VISUALIZER_HOOKS_SUBDIR);
    let vizHooksDirExists = true;
    try {
      await access(vizHooksDir, constants.F_OK);
    } catch {
      vizHooksDirExists = false;
    }

    if (vizHooksDirExists) {
      let remaining: string[] = [];
      try {
        remaining = await readdir(vizHooksDir);
      } catch {
        // ignore
      }
      if (remaining.length === 0) {
        if (options.apply) {
          await rm(vizHooksDir, { recursive: true, force: true });
        }
        deletedStubs.push(`.github/hooks/${VISUALIZER_HOOKS_SUBDIR}/`);
      }
    }
  }

  let visualizerExists = true;
  try {
    await access(vizDir, constants.F_OK);
  } catch {
    visualizerExists = false;
  }

  if (visualizerExists && options.apply) {
    await rm(vizDir, { recursive: true, force: true });
  }

  console.log(`\nUnbootstrap mode: ${options.apply ? "apply" : "dry-run"}`);
  console.log(`Target repo: ${targetRepo}`);
  console.log(`\nHook scripts patched: ${scriptChanges.length}`);
  for (const item of scriptChanges) {
    console.log(`  ${options.apply ? "PATCH" : "WOULD PATCH"} ${item}`);
  }

  console.log(`\nGenerated stubs deleted: ${deletedStubs.length}`);
  for (const item of deletedStubs) {
    console.log(`  ${options.apply ? "DELETE" : "WOULD DELETE"} ${item}`);
  }

  console.log(`\nManifests updated: ${manifestChanges.length}`);
  for (const item of manifestChanges) {
    console.log(`  ${options.apply ? "PATCH" : "WOULD PATCH"} ${item}`);
  }

  if (skipped.length > 0) {
    console.log(`\nSkipped: ${skipped.length}`);
    for (const item of skipped) {
      console.log(`  SKIP ${item}`);
    }
  }

  if (visualizerExists) {
    console.log(`\n${options.apply ? "DELETE" : "WOULD DELETE"} .visualizer/`);
  } else {
    console.log("\nOK .visualizer/ not present");
  }

  if (!options.apply) {
    console.log("\nDry-run only. Re-run with --apply to perform changes.");
  }
}

/* istanbul ignore next -- entry guard */
if (process.argv[1] && resolve(process.argv[1]) === resolve(import.meta.filename ?? "")) {
  void main();
}
