import { describe, expect, it } from "vitest";
import {
  isAutoGeneratedStubContent,
  removeBootstrapManifestEntries,
  stripVisualizerEmitBlocks,
} from "../unbootstrap-existing-repo.js";

describe("stripVisualizerEmitBlocks", () => {
  it("removes the auto-wired emit block and keeps user logic", () => {
    const input = `#!/usr/bin/env bash
set -euo pipefail

echo "before"
# --- Visualizer emit (auto-wired by bootstrap-existing-repo) ---
if [ -x "\${REPO_ROOT}/.visualizer/emit-event.sh" ]; then
  _VIZ_PAYLOAD={}
  "\${REPO_ROOT}/.visualizer/emit-event.sh" sessionStart "\${_VIZ_PAYLOAD}" "\${SESSION_ID}" >&2 || true
fi

echo "after"
`;

    const result = stripVisualizerEmitBlocks(input);
    expect(result.removedBlocks).toBe(1);
    expect(result.updated).toContain('echo "before"');
    expect(result.updated).toContain('echo "after"');
    expect(result.updated).not.toContain(".visualizer/emit-event.sh");
  });

  it("does nothing when no marker exists", () => {
    const input = `#!/usr/bin/env bash\necho "hello"\n`;
    const result = stripVisualizerEmitBlocks(input);
    expect(result.removedBlocks).toBe(0);
    expect(result.updated).toBe(input);
  });

  it("removes a PowerShell auto-wired emit block", () => {
    const input = `# PowerShell hook
Write-Host "before"
# --- Visualizer emit (auto-wired by bootstrap-existing-repo) ---
$_vizEmitScript = Join-Path $RepoRoot ".visualizer/emit-event.ps1"
if (Test-Path $_vizEmitScript) {
  try {
    $_vizPayload = '{}'
    & $_vizEmitScript -EventType "sessionStart" -Payload $_vizPayload -SessionId "run-1" 2>&1 | Out-Null
  } catch { }
}

Write-Host "after"
`;

    const result = stripVisualizerEmitBlocks(input);
    expect(result.removedBlocks).toBe(1);
    expect(result.updated).toContain('Write-Host "before"');
    expect(result.updated).toContain('Write-Host "after"');
    expect(result.updated).not.toContain("emit-event.ps1");
  });

  it("removes a PowerShell emit block with stdin extraction", () => {
    const input = `# PowerShell hook
Write-Host "before"

# --- Visualizer emit (auto-wired by bootstrap-existing-repo) ---
# Read Copilot CLI context from stdin (JSON payload)
$_vizStdin = try { $input | Out-String } catch { '{}' }
if (-not $_vizStdin) { $_vizStdin = '{}' }
$_vizJson = try { $_vizStdin | ConvertFrom-Json } catch { $null }
function _vizField([string[]]$names) { if (-not $_vizJson) { return '' }; foreach ($n in $names) { $v = $_vizJson.PSObject.Properties[$n]; if ($v -and $v.Value) { return [string]$v.Value } }; return '' }
# Extract fields from stdin JSON into env vars (stdin fills unset vars)
if (-not $env:TOOL_NAME)              { $env:TOOL_NAME = _vizField 'tool_name','toolName' }
if (-not $env:SESSION_ID)             { $env:SESSION_ID = _vizField 'session_id','sessionId' }
$_vizEmitScript = Join-Path $RepoRoot ".visualizer/emit-event.ps1"
if (Test-Path $_vizEmitScript) {
  try {
    $_vizPayload = '{}'
    & $_vizEmitScript -EventType "sessionStart" -Payload $_vizPayload -SessionId "run-1" 2>&1 | Out-Null
  } catch { }
}

Write-Host "after"
`;

    const result = stripVisualizerEmitBlocks(input);
    expect(result.removedBlocks).toBe(1);
    expect(result.updated).toContain('Write-Host "before"');
    expect(result.updated).toContain('Write-Host "after"');
    expect(result.updated).not.toContain("emit-event.ps1");
    expect(result.updated).not.toContain("_vizStdin");
    expect(result.updated).not.toContain("_vizField");
  });
});

describe("isAutoGeneratedStubContent", () => {
  it("identifies canonical generated stub content", () => {
    const content = `#!/usr/bin/env bash
set -euo pipefail
# Stub hook generated by bootstrap-existing-repo.
# Add your custom logic above the visualizer emit block below.

SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "\$SCRIPT_DIR/../../.." && pwd)"

exit 0
`;

    expect(isAutoGeneratedStubContent(content)).toBe(true);
  });

  it("identifies legacy generated stub content with 2-level REPO_ROOT", () => {
    const content = `#!/usr/bin/env bash
set -euo pipefail
# Stub hook generated by bootstrap-existing-repo.
# Add your custom logic above the visualizer emit block below.

SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "\$SCRIPT_DIR/../.." && pwd)"

exit 0
`;

    expect(isAutoGeneratedStubContent(content)).toBe(true);
  });

  it("identifies new format stubs with stdin extraction block", () => {
    const content = `#!/usr/bin/env bash
set -euo pipefail
# Stub hook generated by bootstrap-existing-repo.
# Copilot CLI passes hook context as JSON on stdin.
# Add your custom logic above the visualizer emit block below.

SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "\$SCRIPT_DIR/../../.." && pwd)"

# Read Copilot CLI context from stdin (JSON payload)
_VIZ_STDIN=$(cat 2>/dev/null || echo '{}')
if [ -z "$_VIZ_STDIN" ]; then _VIZ_STDIN='{}'; fi
_vjq() { echo "$_VIZ_STDIN" | jq -r "$1" 2>/dev/null || true; }
# Extract fields from stdin JSON into env vars (stdin fills unset vars)
: "\${TOOL_NAME:=$(_vjq '.tool_name // .toolName // empty')}"
: "\${SESSION_ID:=$(_vjq '.session_id // .sessionId // empty')}"
: "\${AGENT_NAME:=$(_vjq '.agent_name // .agentName // .name // empty')}"

exit 0
`;

    expect(isAutoGeneratedStubContent(content)).toBe(true);
  });

  it("identifies canonical generated PowerShell stub content", () => {
    const content = `# Stub hook generated by bootstrap-existing-repo.
# Add your custom logic above the visualizer emit block below.
$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = (Resolve-Path (Join-Path $ScriptDir ".." ".." "..")).Path

exit 0
`;

    expect(isAutoGeneratedStubContent(content)).toBe(true);
  });

  it("rejects stubs with custom logic", () => {
    const content = `#!/usr/bin/env bash
set -euo pipefail
# Stub hook generated by bootstrap-existing-repo.
# Add your custom logic above the visualizer emit block below.
SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "\$SCRIPT_DIR/../.." && pwd)"
echo "custom"
exit 0
`;

    expect(isAutoGeneratedStubContent(content)).toBe(false);
  });

  it("rejects new format stubs with custom user logic", () => {
    const content = `#!/usr/bin/env bash
set -euo pipefail
# Stub hook generated by bootstrap-existing-repo.
# Copilot CLI passes hook context as JSON on stdin.
SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "\$SCRIPT_DIR/../../.." && pwd)"
_VIZ_STDIN=$(cat 2>/dev/null || echo '{}')
echo "my custom processing"
exit 0
`;

    expect(isAutoGeneratedStubContent(content)).toBe(false);
  });

  it("rejects PowerShell stubs with custom logic", () => {
    const content = `# Stub hook generated by bootstrap-existing-repo.
# Add your custom logic above the visualizer emit block below.
$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = (Resolve-Path (Join-Path $ScriptDir ".." ".." "..")).Path
Write-Host "custom"
exit 0
`;

    expect(isAutoGeneratedStubContent(content)).toBe(false);
  });

  it("identifies new format PowerShell stubs with stdin extraction block", () => {
    const content = `# Stub hook generated by bootstrap-existing-repo.
# Copilot CLI passes hook context as JSON on stdin.
# Add your custom logic above the visualizer emit block below.
$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = (Resolve-Path (Join-Path $ScriptDir ".." ".." "..")).Path

# Read Copilot CLI context from stdin (JSON payload)
$_vizStdin = try { $input | Out-String } catch { '{}' }
if (-not $_vizStdin) { $_vizStdin = '{}' }
$_vizJson = try { $_vizStdin | ConvertFrom-Json } catch { $null }
function _vizField([string[]]$names) { if (-not $_vizJson) { return '' }; foreach ($n in $names) { $v = $_vizJson.PSObject.Properties[$n]; if ($v -and $v.Value) { return [string]$v.Value } }; return '' }
# Extract fields from stdin JSON into env vars (stdin fills unset vars)
if (-not $env:TOOL_NAME)              { $env:TOOL_NAME = _vizField 'tool_name','toolName' }
if (-not $env:SESSION_ID)             { $env:SESSION_ID = _vizField 'session_id','sessionId' }

exit 0
`;

    expect(isAutoGeneratedStubContent(content)).toBe(true);
  });

  it("rejects new format PowerShell stubs with custom user logic", () => {
    const content = `# Stub hook generated by bootstrap-existing-repo.
# Copilot CLI passes hook context as JSON on stdin.
# Add your custom logic above the visualizer emit block below.
$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = (Resolve-Path (Join-Path $ScriptDir ".." ".." "..")).Path
$_vizStdin = try { $input | Out-String } catch { '{}' }
Write-Host "my custom processing"
exit 0
`;

    expect(isAutoGeneratedStubContent(content)).toBe(false);
  });
});

describe("removeBootstrapManifestEntries", () => {
  it("removes bootstrap-managed commands and preserves unrelated entries", () => {
    const manifest = {
      version: 1,
      hooks: {
        sessionStart: [
          { type: "command", bash: "./.github/hooks/visualizer/session-start.sh", cwd: ".", timeoutSec: 15 },
          { type: "command", bash: "./scripts/custom-hook.sh" },
        ],
        customEvent: [
          { type: "command", bash: "./scripts/another.sh" },
        ],
      },
    };

    const result = removeBootstrapManifestEntries(manifest);
    expect(result.changed).toBe(true);
    expect(result.removedEvents).toEqual(["sessionStart"]);

    const hooks = result.updated.hooks as Record<string, unknown>;
    const sessionStart = hooks.sessionStart as Array<Record<string, unknown>>;
    expect(sessionStart).toHaveLength(1);
    expect(sessionStart[0]?.bash).toBe("./scripts/custom-hook.sh");
    expect(hooks.customEvent).toBeDefined();
  });

  it("supports prefixed hook paths", () => {
    const manifest = {
      hooks: {
        preToolUse: [
          { type: "command", bash: "./.github/hooks/visualizer/viz-pre-tool-use.sh" },
        ],
      },
    };

    const result = removeBootstrapManifestEntries(manifest, "viz");
    expect(result.changed).toBe(true);
    expect(result.removedEvents).toEqual(["preToolUse"]);
    expect((result.updated.hooks as Record<string, unknown>).preToolUse).toBeUndefined();
  });

  it("returns unchanged for incompatible manifest shapes", () => {
    const result = removeBootstrapManifestEntries({ version: 1 });
    expect(result.changed).toBe(false);
    expect(result.removedEvents).toEqual([]);
  });

  it("removes entries for new event types (postToolUseFailure, agentStop, notification, errorOccurred)", () => {
    const manifest = {
      version: 1,
      hooks: {
        postToolUseFailure: [
          { type: "command", bash: "./.github/hooks/visualizer/post-tool-use-failure.sh" },
        ],
        agentStop: [
          { type: "command", bash: "./.github/hooks/visualizer/agent-stop.sh" },
        ],
        notification: [
          { type: "command", bash: "./.github/hooks/visualizer/notification.sh" },
        ],
        errorOccurred: [
          { type: "command", bash: "./.github/hooks/visualizer/error-occurred.sh" },
        ],
      },
    };

    const result = removeBootstrapManifestEntries(manifest);
    expect(result.changed).toBe(true);
    expect(result.removedEvents).toEqual([
      "postToolUseFailure",
      "agentStop",
      "notification",
      "errorOccurred",
    ]);
    const hooks = result.updated.hooks as Record<string, unknown>;
    expect(hooks.postToolUseFailure).toBeUndefined();
    expect(hooks.agentStop).toBeUndefined();
    expect(hooks.notification).toBeUndefined();
    expect(hooks.errorOccurred).toBeUndefined();
  });

  it("removes prefixed entries for new event types", () => {
    const manifest = {
      hooks: {
        postToolUseFailure: [
          { type: "command", bash: "./.github/hooks/visualizer/viz-post-tool-use-failure.sh" },
        ],
        errorOccurred: [
          { type: "command", bash: "./.github/hooks/visualizer/viz-error-occurred.sh" },
        ],
      },
    };

    const result = removeBootstrapManifestEntries(manifest, "viz");
    expect(result.changed).toBe(true);
    expect(result.removedEvents).toEqual(["postToolUseFailure", "errorOccurred"]);
  });

  it("removes legacy entries with old non-subdirectory paths", () => {
    const manifest = {
      version: 1,
      hooks: {
        sessionStart: [
          { type: "command", bash: "./.github/hooks/session-start.sh", cwd: ".", timeoutSec: 15 },
        ],
        preToolUse: [
          { type: "command", bash: "./.github/hooks/pre-tool-use.sh" },
        ],
      },
    };

    const result = removeBootstrapManifestEntries(manifest);
    expect(result.changed).toBe(true);
    expect(result.removedEvents).toEqual(["sessionStart", "preToolUse"]);
  });

  it("removes manifest entries with powershell property", () => {
    const manifest = {
      version: 1,
      hooks: {
        sessionStart: [
          { type: "command", bash: "./.github/hooks/visualizer/session-start.sh", powershell: "./.github/hooks/visualizer/session-start.ps1" },
        ],
        preToolUse: [
          { type: "command", bash: "./.github/hooks/visualizer/pre-tool-use.sh", powershell: "./.github/hooks/visualizer/pre-tool-use.ps1" },
          { type: "command", bash: "./scripts/custom-hook.sh" },
        ],
      },
    };

    const result = removeBootstrapManifestEntries(manifest);
    expect(result.changed).toBe(true);
    expect(result.removedEvents).toEqual(["sessionStart", "preToolUse"]);
    const hooks = result.updated.hooks as Record<string, unknown>;
    expect(hooks.sessionStart).toBeUndefined();
    const preToolUse = hooks.preToolUse as Array<Record<string, unknown>>;
    expect(preToolUse).toHaveLength(1);
    expect(preToolUse[0]?.bash).toBe("./scripts/custom-hook.sh");
  });
});
